# Generated by Django 4.2.1 on 2023-05-22 17:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gym_app', '0003_alter_profile_age_alter_profile_height_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(max_length=512)),
                ('trainers', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
