# Generated by Django 4.2.1 on 2023-05-28 15:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gym_app', '0006_membership_usermembership_membershiphistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='capacity',
            field=models.PositiveIntegerField(default=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='training',
            name='trainers',
            field=models.ManyToManyField(limit_choices_to={'groups__name': 'trainer_group'}, to=settings.AUTH_USER_MODEL),
        ),
    ]
