# Generated by Django 4.2.1 on 2023-05-28 16:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gym_app', '0007_training_capacity_alter_training_trainers'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='registered_users',
            field=models.ManyToManyField(blank=True, related_name='registered_trainings', to=settings.AUTH_USER_MODEL),
        ),
    ]
